// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/audio.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_proto_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_proto_audio_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AudioChunk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_audio_proto protoreflect.FileDescriptor

const file_proto_audio_proto_rawDesc = "" +
	"\n" +
	"\x11proto/audio.proto\x12\x05audio\"[\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2G\n" +
	"\fAudioService\x127\n" +
	"\vStreamAudio\x12\x11.audio.AudioChunk\x1a\x11.audio.AudioChunk(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_audio_proto_rawDescOnce sync.Once
	file_proto_audio_proto_rawDescData []byte
)

func file_proto_audio_proto_rawDescGZIP() []byte {
	file_proto_audio_proto_rawDescOnce.Do(func() {
		file_proto_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_audio_proto_rawDesc), len(file_proto_audio_proto_rawDesc)))
	})
	return file_proto_audio_proto_rawDescData
}

var file_proto_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_audio_proto_goTypes = []any{
	(*AudioChunk)(nil), // 0: audio.AudioChunk
}
var file_proto_audio_proto_depIdxs = []int32{
	0, // 0: audio.AudioService.StreamAudio:input_type -> audio.AudioChunk
	0, // 1: audio.AudioService.StreamAudio:output_type -> audio.AudioChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_audio_proto_init() }
func file_proto_audio_proto_init() {
	if File_proto_audio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_audio_proto_rawDesc), len(file_proto_audio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_audio_proto_goTypes,
		DependencyIndexes: file_proto_audio_proto_depIdxs,
		MessageInfos:      file_proto_audio_proto_msgTypes,
	}.Build()
	File_proto_audio_proto = out.File
	file_proto_audio_proto_goTypes = nil
	file_proto_audio_proto_depIdxs = nil
}
